channels:
- conda-forge
dependencies:
- python=3.11.14
- pip<=24.0
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - jaraco-collections==5.1.0
  - matplotlib==3.7.5
  - numpy==1.26.4
  - pandas==2.1.4
  - pyarrow==22.0.0
  - pycaret==3.3.2
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
